[tools]
clojure = "1.12.0.1479"
rust-analyzer = "2025-04-07"
rust = "nightly-2025-04-07"
java = "temurin-21.0.4+7.0.LTS"
go = "1.22.0"
python = "3.11.3"
maven = "3.9.1"
nim = "2.0.8"
node = "22.19.0"
neovim = "nightly"
kubectl = "1.32.2"
kubectx = "0.9.5"
taplo = "0.10.0"

[alias.java.versions]

graal = 'graalvm-community-21.0.2'
temurin = 'temurin-21.0.4+7.0.LTS'

[settings]
idiomatic_version_file_enable_tools = ["node"]
